INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (1, 'Craiova', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (2, 'Cluj-Napoca', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (3, 'Bucharest', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (4, 'Iasi', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (5, 'Hico', 5);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (6, 'Brasov', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (7, 'Filiasi', 1);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (8, 'Berlin', 2);
INSERT INTO bookstore.city (ID, Name, Country_ID) VALUES (9, 'Aarhus', 8);