INSERT INTO bookstore.genre (ID, Genre) VALUES (1, 'Action');
INSERT INTO bookstore.genre (ID, Genre) VALUES (2, 'Adventure');
INSERT INTO bookstore.genre (ID, Genre) VALUES (14, 'Art');
INSERT INTO bookstore.genre (ID, Genre) VALUES (17, 'Biography');
INSERT INTO bookstore.genre (ID, Genre) VALUES (22, 'Buildungsroman');
INSERT INTO bookstore.genre (ID, Genre) VALUES (3, 'Children');
INSERT INTO bookstore.genre (ID, Genre) VALUES (4, 'Classic');
INSERT INTO bookstore.genre (ID, Genre) VALUES (5, 'Comic');
INSERT INTO bookstore.genre (ID, Genre) VALUES (6, 'Drama');
INSERT INTO bookstore.genre (ID, Genre) VALUES (8, 'Fantasy');
INSERT INTO bookstore.genre (ID, Genre) VALUES (15, 'Fiction');
INSERT INTO bookstore.genre (ID, Genre) VALUES (18, 'History');
INSERT INTO bookstore.genre (ID, Genre) VALUES (9, 'Horror');
INSERT INTO bookstore.genre (ID, Genre) VALUES (23, 'Mystery');
INSERT INTO bookstore.genre (ID, Genre) VALUES (16, 'Non-Fiction');
INSERT INTO bookstore.genre (ID, Genre) VALUES (19, 'Philosophy');
INSERT INTO bookstore.genre (ID, Genre) VALUES (11, 'Poetry');
INSERT INTO bookstore.genre (ID, Genre) VALUES (21, 'Prayer');
INSERT INTO bookstore.genre (ID, Genre) VALUES (10, 'Romance');
INSERT INTO bookstore.genre (ID, Genre) VALUES (20, 'Science');
INSERT INTO bookstore.genre (ID, Genre) VALUES (12, 'Science Fiction');
INSERT INTO bookstore.genre (ID, Genre) VALUES (7, 'Thriller');
INSERT INTO bookstore.genre (ID, Genre) VALUES (13, 'Young Adult');